### ISSUE TITLE
Add postcss-pixtorem

### ISSUE THREAD

**Issue by robneu** [wpsitecare/sitecare-theme-config#5]
I hate using relative values when writing CSS. I find it much easier to define sizes in pixels, mostly because it's the way I've worked for years and I don't feel like re-training my brain to another unit.

That said, I recognize that relative units do have benefits, so I'd like to try to get [node-pixrem](https://github.com/robwierzbowski/node-pixrem) working through grunt-postcss. I tried loading it in, but for whatever reason I couldn't get it to work.

**Comment by ctalkington** [comment]
@robneu i think you were just missing that they should be called as functions like the example here:

https://github.com/nDmitry/grunt-postcss#usage

**Comment by robneu** [comment]
Haha I was just missing parenthesis? 😕

**Comment by ctalkington** [comment]
yah, though im not sure that package does what you're thinking as it sets px fallbacks from rem values not the reverse.

this might be closer to desired?
https://github.com/ggkovacs/node-px2rem

**Comment by ctalkington** [comment]
also from: http://postcss.parts/

https://github.com/cuth/postcss-pxtorem

**Comment by robneu** [comment]
Ah, yeah thanks man! https://github.com/cuth/postcss-pxtorem is the one I mean to test out originally. I'll give this another try today.

**Comment by robneu** [comment]
Seems like this is working as-expected. Thanks for the help @ctalkington!
