### ISSUE TITLE
Release alias bumps stylesheet one version higher than the project

### ISSUE THREAD

**Issue by robneu** [wpsitecare/sitecare-theme-config#6]
This only happens when running `grunt release:major`, `grunt release:minor`, `grunt release:patch` tasks. Running the same task directly like `grunt version::major` works as-expected.

**Comment by ctalkington** [comment]
mainly as grunt-version checks args passed to Grunt. looks like you've fixed it based on my suggestion ;)

**Comment by robneu** [comment]
Yup! I think that fixed it, but need to double-check.
