### ISSUE TITLE
consider using package vs pkg

### ISSUE THREAD

**Issue by ctalkington** [wpsitecare/sitecare-theme-config#7]
this is something I came across digging into another issue I was having.

https://github.com/talkingtontech/wp-theme-config/commit/4d9a0593e575a596dbe1ec37ad4367986d15f99f

essentially load-grunt-config does the initial package.json read for you so by using and updating its var you avoid extra fs read off the bat.

**Comment by robneu** [comment]
That looks :+1: to me. I'll make that change unless you want to send a PR for it.

**Comment by robneu** [comment]
@ctalkington This is a little off-topic, but how do you test your config locally? I've tried using `npm-link` in the past but couldn't get it working so I wind up just pushing crap to the repo even if it's not fully tested.

**Comment by ctalkington** [comment]
sadly, i haven't worked anything too scientific, usually i make changes based on something i noticed in consuming project so ill edit its local node_modules and copy that dir back to config repo once im happy. in other words, trial and error.

i have debated adding a travis to the config repo that runs a sample or something.

**Comment by ctalkington** [comment]
you also can remove:

https://github.com/wpsitecare/alpha/blob/685acbfadd4d2725eef19bc0df43320521f33f00/gruntfile.js#L8

now as `package` is auto set and your just updating with `readpkg`

**Comment by robneu** [comment]
:+1: Looks like this is all good!
